language: node_js
sudo: false
node_js:
- '12'
env:
  global:
  - LOG_TEST_COVERAGE=true
cache: yarn
script: yarn run test
before_deploy: yarn run build
deploy:
  provider: npm
  email: sendstufftokevin@gmail.com
  on:
    branch: master
    tags: true
  skip_cleanup: true
  edge: true
  api_key:
    secure: Y6B6O6+OWGKrK8ECmHPMp3CiBFtggsnX8R8ZF3L2yyXQX5bhlo52Px6Ae8dxOE95bRdruK6ssUzSzcZqNqBQMXChqNmP62c9lzrkPeCfgWzUh48cVxhCfCGlWV7ejbRvs8qFaGodt//epZsB4zfNpAx3aOL3ukrtcuHb6C5tWuv6k8Ww9Jxeji0KkAb10SLp0cVn3bhVhbBB0QZWIsKvOHM35S5f/a3ki1MHTYryyDXRdteQV9mR6V9ocZ1rL8WR4MemCwPrIQplNjG7dZmHpb5A84gfVs2UwlBqkE2JB6qTYrnRuw7HZJfULIJjvai+PWYiBmsj/qPLckFw0pYjG0RQCS5GltGE7X1oN3/bCnXH32MXbeBB//3Fh+YEkYFYdUrUSR7fgXxik73yucJ6EucuEb0qTmsQVNLvxb+OoVCH7IMfgErVbHm5rHMObuv8zu6W9KEITa7oKttUAg7FH+2kX9J2R2rDIGwo7hpLk5HykjHoUc4yosBwsS/x5fCmtxSOq+HIf1+4H3wGGdIA5aYxChU6QFLmxfl2o/jrxDmfaeFpMWIS1cBnzyDhpSCZGPigJ+Q0+x7/u5A99CUXW+gBObXj2I7xaHn0/zo75fLYCS2my2VvtDN+3e7EKKueqKVSHuBZPdBg9EpgkPa4hp3b8mnV6Fg8X4+SViuPTLE=
